### ISSUE TITLE
Lavalink4NET.DSharpPlus 3.0.0 seems to be incompatible with DSharpPlus versions above 4.3.0

### ISSUE THREAD

**Issue by Silverdimond** [angelobreuer/Lavalink4NET#119]
```
System.TypeLoadException: GenericArguments[1], 'DSharpPlus.EventArgs.VoiceStateUpdateEventArgs', on 'Emzi0767.Utilities.AsyncEventHandler`2[TSender,TArgs]' violates the constraint of type parameter 'TArgs'.
   at Lavalink4NET.DSharpPlus.DiscordClientWrapper..ctor(DiscordClient client)
```
occurs when using  Lavalink4NET.DSharpPlus 3.0.0 with any DSharpPlus version over 4.3.0, (tested 4.3.0 works, 4.4.0 4.4.1  and 5.0.0-nightly-01581 do not)

1. Clone https://github.com/angelobreuer/Lavalink4NET
2. Open samples/Lavalink4NET.DSharpPlus.ExampleBot/Lavalink4NET.DSharpPlus.ExampleBot.csproj
3. change framework to net7.0, explicitly specify a higher version of DSharpPlus
```diff
diff --git a/samples/Lavalink4NET.DSharpPlus.ExampleBot/Lavalink4NET.DSharpPlus.ExampleBot.csproj b/samples/Lavalink4NET.DSharpPlus.ExampleBot/Lavalink4NET.DSharpPlus.ExampleBot.csproj
index 46c3d24..430bbb8 100644
--- a/samples/Lavalink4NET.DSharpPlus.ExampleBot/Lavalink4NET.DSharpPlus.ExampleBot.csproj
+++ b/samples/Lavalink4NET.DSharpPlus.ExampleBot/Lavalink4NET.DSharpPlus.ExampleBot.csproj
@@ -2,16 +2,18 @@
 
   <PropertyGroup>
     <OutputType>Exe</OutputType>
-    <TargetFramework>net6.0</TargetFramework>
+    <TargetFramework>net7.0</TargetFramework>
   </PropertyGroup>
 
   <ItemGroup>
-    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.0" />
-    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="6.0.0" />
+    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="7.0.0" />
+    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="7.0.0" />
+    <PackageReference Include="DSharpPlus" Version="5.0.0-nightly-01581"/>
+    <PackageReference Include="Emzi0767.Common" Version="2.6.2"/>
   </ItemGroup>
 
   <ItemGroup>
     <ProjectReference Include="..\..\src\Lavalink4NET.DSharpPlus\Lavalink4NET.DSharpPlus.csproj" />
     <ProjectReference Include="..\..\src\Lavalink4NET.MemoryCache\Lavalink4NET.MemoryCache.csproj" />
   </ItemGroup>
</Project>
```
4. Open Program.cs change token, resturi, password, websocketuri
5. dotnet run, and see the error
Lavalink4NET Version 3.0.0 

Bypassing that exception is as simple as changing a version string to 4.3.0, but other bigger problems are waiting down the road
```
[2023-06-03 17:48:37 +02:00] [104 /EventHandler] [Error] Event handler exception for event VOICE_SERVER_UPDATED thrown from System.Threading.Tasks.Task OnVoiceServerUpdated(DSharpPlus.DiscordClient, DSharpPlus.EventArgs.VoiceServerUpdateEventArgs) (defined in Lavalink4NET.DSharpPlus.DiscordClientWrapperBase)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Lavalink4NET.DSharpPlus.DSharpUtil.GetVoiceToken(VoiceServerUpdateEventArgs voiceServerUpdateEventArgs) in /home/silver/Lavalink4NET/src/Lavalink4NET.DSharpPlus/DSharpUtil.cs:line 76
   at Lavalink4NET.DSharpPlus.DiscordClientWrapperBase.OnVoiceServerUpdated(DiscordClient _, VoiceServerUpdateEventArgs voiceServer) in /home/silver/Lavalink4NET/src/Lavalink4NET.DSharpPlus/DiscordClientWrapperBase.cs:line 146
   at DSharpPlus.AsyncEvents.AsyncEvent`2.<>c__DisplayClass7_0.<<InvokeAsync>b__0>d.MoveNext()
```
VoiceToken is now public (at least on 4.4.1) https://github.com/DSharpPlus/DSharpPlus/blob/master/DSharpPlus/EventArgs/Voice/VoiceServerUpdateEventArgs.cs#L46
```diff
index 4f9859f..ddd2921 100644
--- a/src/Lavalink4NET.DSharpPlus/DSharpUtil.cs
+++ b/src/Lavalink4NET.DSharpPlus/DSharpUtil.cs
@@ -41,21 +41,15 @@ namespace Lavalink4NET.DSharpPlus
         /// <summary>
         ///     The internal "SessionId" property info in <see cref="DiscordVoiceState"/>.
         /// </summary>
-        // https://github.com/DSharpPlus/DSharpPlus/blob/master/DSharpPlus/Entities/DiscordVoiceState.cs#L70
+        // https://github.com/DSharpPlus/DSharpPlus/blob/master/DSharpPlus/Entities/Voice/DiscordVoiceState.cs#L95
         private static readonly PropertyInfo _sessionIdProperty = typeof(DiscordVoiceState)
             .GetProperty("SessionId", BindingFlags.NonPublic | BindingFlags.Instance);
 
-        /// <summary>
-        ///     The internal "VoiceToken" property info in <see cref="VoiceServerUpdateEventArgs"/>.
-        /// </summary>
-        // https://github.com/DSharpPlus/DSharpPlus/blob/master/DSharpPlus/EventArgs/VoiceServerUpdateEventArgs.cs#L24
-        private static readonly PropertyInfo _voiceTokenProperty = typeof(VoiceServerUpdateEventArgs)
-            .GetProperty("VoiceToken", BindingFlags.NonPublic | BindingFlags.Instance);
-
+     
         /// <summary>
         ///     The internal "_webSocketClient" field info in <see cref="DiscordClient"/>.
         /// </summary>
-        // https://github.com/DSharpPlus/DSharpPlus/blob/master/DSharpPlus/DiscordClient.cs#L36
+        // https://github.com/DSharpPlus/DSharpPlus/blob/master/DSharpPlus/Clients/DiscordClient.WebSocket.cs#L54
         private static readonly FieldInfo _webSocketClientField = typeof(DiscordClient)
             .GetField("_webSocketClient", BindingFlags.NonPublic | BindingFlags.Instance);
 
@@ -67,13 +61,6 @@ namespace Lavalink4NET.DSharpPlus
         public static string GetSessionId(this DiscordVoiceState voiceState)
             => (string)_sessionIdProperty.GetValue(voiceState);
 
-        /// <summary>
-        ///     Gets the "VoiceToken" property value of the specified <paramref name="voiceServerUpdateEventArgs"/>.
-        /// </summary>
-        /// <param name="voiceServerUpdateEventArgs">the instance</param>
-        /// <returns>the "VoiceToken" value</returns>
-        public static string GetVoiceToken(this VoiceServerUpdateEventArgs voiceServerUpdateEventArgs)
-            => (string)_voiceTokenProperty.GetValue(voiceServerUpdateEventArgs);
 
         /// <summary>
         ///     Gets the internal "_webSocketClient" field value of the specified <paramref name="client"/>.
```
```diff
--- a/src/Lavalink4NET.DSharpPlus/DiscordClientWrapperBase.cs
+++ b/src/Lavalink4NET.DSharpPlus/DiscordClientWrapperBase.cs
@@ -143,7 +143,7 @@ public abstract class DiscordClientWrapperBase : IDiscordClientWrapper
     /// <exception cref="ObjectDisposedException">thrown if the instance is disposed</exception>
     protected Task OnVoiceServerUpdated(DiscordClient _, VoiceServerUpdateEventArgs voiceServer)
     {
-        var args = new VoiceServer(voiceServer.Guild.Id, voiceServer.GetVoiceToken(), voiceServer.Endpoint);
+        var args = new VoiceServer(voiceServer.Guild.Id, voiceServer.VoiceToken, voiceServer.Endpoint);
         return VoiceServerUpdated.InvokeAsync(this, args);
     }
 
diff --git a/src/Lavalink4NET.DSharpPlus/Lavalink4NET.DSharpPlus.csproj b/src/Lavalink4NET.DSharpPlus/Lavalink4NET.DSharpPlus.csproj
index a11a107..dc3c91a 100644
--- a/src/Lavalink4NET.DSharpPlus/Lavalink4NET.DSharpPlus.csproj
+++ b/src/Lavalink4NET.DSharpPlus/Lavalink4NET.DSharpPlus.csproj
@@ -17,7 +17,7 @@
   </PropertyGroup>
 
   <ItemGroup>
-    <PackageReference Include="DSharpPlus" Version="4.2.0-nightly-01026" />
+    <PackageReference Include="DSharpPlus" Version="4.4.1" />
     <ProjectReference Include="..\Lavalink4NET\Lavalink4NET.csproj" />
   </ItemGroup>
 
```
This seems to solve the issue

**Comment by angelobreuer** [comment]
Thank you! Do you want to file a PR?

**Comment by Silverdimond** [comment]
Sure. I'd be glad to file one.
