### ISSUE TITLE
Error when trying to get the player using Discord.Net

### ISSUE THREAD

**Issue by hadagalberto** [angelobreuer/Lavalink4NET#153]
**Describe the bug**
Can't receive/create the player using Discord.Net, an error is thrown.

**To Reproduce**
1. Created slash command to play a music
2. Use the slash command at Discord
3. The bot joins the voice channel
4. The error is thrown in console

**Expected behavior**
The music should have started playing on the bot that entered the voice call

**Screenshots**
![Error](https://i.imgur.com/IIpAYBl.png)

**(please complete the following information):**
 - Lavalink4NET Version:
 Tried 4.0.18 and 4.0.19-beta.2
 - Exception thrown? (consider enabling logging):
```
 fail: Discord.Interactions.InteractionService[0]
      23:55:10 App Command Discord.Interactions.InteractionException: Error occurred executing play.
       ---> System.TimeoutException: The player could not be retrieved within the specified time. There are a few possibilities why this might occur:
- You are currently operating on the gateway thread which can cause a deadlock since no further gateway messages can be processed.
    - In case you are using Discord.Net, a common solution would be to enable RunMode.Async which dispatches commands on a separate task which allows
      further gateway messages to be processed while the player is being created
- The client lost connection to the Lavalink server.
         at Lavalink4NET.Players.PlayerManager.GetPlayerInternalAsync(ILavalinkPlayerHandle playerHandle, CancellationToken cancellationToken) in /home/runner/work/Lavalink4NET/Lavalink4NET/src/Lavalink4NET/Players/PlayerManager.cs:line 392
         at Lavalink4NET.Players.PlayerManager.JoinAsync[TPlayer,TOptions](UInt64 guildId, UInt64 voiceChannelId, PlayerFactory`2 playerFactory, IOptions`1 options, CancellationToken cancellationToken) in /home/runner/work/Lavalink4NET/Lavalink4NET/src/Lavalink4NET/Players/PlayerManager.cs:line 148
         at Lavalink4NET.Players.PlayerManager.RetrieveAsync[TPlayer,TOptions](UInt64 guildId, Nullable`1 memberVoiceChannel, PlayerFactory`2 playerFactory, IOptions`1 options, PlayerRetrieveOptions retrieveOptions, CancellationToken cancellationToken) in /home/runner/work/Lavalink4NET/Lavalink4NET/src/Lavalink4NET/Players/PlayerManager.cs:line 299
         at CastorDJ.Modules.MusicModule.GetPlayerAsync(Boolean connectToVoiceChannel) in C:\Users\hadag\source\repos\CastorDJ\Modules\MusicModule.cs:line 248
         at CastorDJ.Modules.MusicModule.Play(String query) in C:\Users\hadag\source\repos\CastorDJ\Modules\MusicModule.cs:line 63
         at Discord.Interactions.Builders.ModuleClassBuilder.<>c__DisplayClass11_0.<<CreateCallback>g__ExecuteCallback|1>d.MoveNext()
         --- End of inner exception stack trace ---
```

**Additional context**
I even tried copying the entire example bot class file using Discord.Net, but I still get the same error.
I have uploaded the full repo to [GitHub](https://github.com/hadagalberto/CastorDJ.NET)

        ```
       [SlashCommand("play", description: "Plays music", runMode: RunMode.Async)]
        public async Task Play(string query)
        {
            await DeferAsync().ConfigureAwait(false);

            var player = await GetPlayerAsync(connectToVoiceChannel: true).ConfigureAwait(false);

            if (player is null)
            {
                return;
            }

            var track = await _audioService.Tracks
                .LoadTrackAsync(query, TrackSearchMode.YouTube)
                .ConfigureAwait(false);

            if (track is null)
            {
                await FollowupAsync("😖 No results.").ConfigureAwait(false);
                return;
            }

            var position = await player.PlayAsync(track).ConfigureAwait(false);

            if (position is 0)
            {
                await FollowupAsync($"🔈 Playing: {track.Uri}").ConfigureAwait(false);
            }
            else
            {
                await FollowupAsync($"🔈 Added to queue: {track.Uri}").ConfigureAwait(false);
            }
        }

        private async ValueTask<VoteLavalinkPlayer?> GetPlayerAsync(bool connectToVoiceChannel = true)
        {
            var retrieveOptions = new PlayerRetrieveOptions(
                ChannelBehavior: connectToVoiceChannel ? PlayerChannelBehavior.Join : PlayerChannelBehavior.None);

            var result = await _audioService.Players
                .RetrieveAsync(Context, playerFactory: PlayerFactory.Vote, retrieveOptions)
                .ConfigureAwait(false);

            if (!result.IsSuccess)
            {
                var errorMessage = result.Status switch
                {
                    PlayerRetrieveStatus.UserNotInVoiceChannel => "You are not connected to a voice channel.",
                    PlayerRetrieveStatus.BotNotConnected => "The bot is currently not connected.",
                    _ => "Unknown error.",
                };

                await FollowupAsync(errorMessage).ConfigureAwait(false);
                return null;
            }

            return result.Player;
        }
```

**Comment by angelobreuer** [comment]
Hi @hadagalberto ,

I had a look at your repository and cloned it and tried it locally. I only had problems with the `GuildVoiceStates` intent not being specified. Once I added it, it worked perfectly here.

I made a PR on your repository. Can you try pulling the changes and see if it works for you?

https://github.com/hadagalberto/CastorDJ.NET/pull/1

> My solution however does not match your problem statement since you are stating that the bot is connecting to the voice channel and also detects other voice states. Therefore, I am not sure, if this is the right solution but that is the fix that fixed it for me locally so I think it might be worth giving a try.

**Comment by hadagalberto** [comment]
It works perfectly, thanks a lot!

**Comment by hadagalberto** [comment]
It works perfectly, thanks a lot!

**Comment by angelobreuer** [comment]
I also added the problem you experienced to be included in the error message, so new users will have a better understanding why the problem might arise:

https://github.com/angelobreuer/Lavalink4NET/blob/511e6d8a765c4b473fb260061ccaa6d56d5c5ae5/src/Lavalink4NET/Players/PlayerManager.cs#L399
