### ISSUE TITLE
Bad Payload when the Lavalink node has more than 2gb reservable memory

### ISSUE THREAD

**Issue by Mijago** [angelobreuer/Lavalink4NET#2]
Hello,

I just tried out this library and just got this tiny error. It does not affect my usage of this nice library, but I thought you might want to know:

```
Received bad payload: {"playingPlayers":0,"op":"stats","memory":{"reservable":4151836672,"used":25529976,"free":15704456,"allocated":41234432},"players":0,"cpu":{"cores":10,"systemLoad":0.07831206290252479,"lavalinkLoad":0.11399947957325007},"uptime":4694308}.
Newtonsoft.Json.JsonReaderException: Could not convert to integer: 4151836672. Path 'memory.reservable'. ---> System.OverflowException: Value was either too large or too small for an Int32.
   at System.Convert.ThrowInt32OverflowException()
   at System.Convert.ToInt32(Int64 value)
   at Newtonsoft.Json.JsonReader.ReadAsInt32()
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.JsonReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Lavalink4NET.Payloads.PayloadConverter.ReadPayload(String json)
   at Lavalink4NET.LavalinkSocket.ProcessNextPayload()
```

https://github.com/angelobreuer/Lavalink4NET/blob/440d453e018dad69fa8b31cedb932562817681ae/src/Lavalink4NET/Statistics/MemoryStatistics.cs#L58-L59
I think the problem is that the code allocates an int32 (signed, so the max value is 2147483647, approximately 2 gigabytes). If the Lavalink node always uses 32 bit (so the process should only have 4gb), an unsigned int may suffice, otherwise a larger type may be better.

**Comment by angelobreuer** [comment]
f2030fe349afb1f7951212bf15557a9247b51474 Thanks for reporting. Hope, no one does have 16384 Pebibytes of RAM 😊
