### ISSUE TITLE
IEnumerable`1<DiscordMember> DiscordChannel.get_Users() returns a method not found bricking Lavalink4nets voting features

### ISSUE THREAD

**Issue by Silverdimond** [angelobreuer/Lavalink4NET#80]
**Describe the bug**
While executing `VoteLavalinkPlayer.VoteAsync(UInt64 userId, Single percentage)` it tries to run a method that can not be found in the latest dsharpplus version (`4.2.0-nightly-00987` and some other newer ones)

**To Reproduce**
1. Make sure to use a new nightly version of DSharpPlus
2. Make a VoteLavalinkPlayer
3. Execute VoteAsync on it

**Expected behavior**
No error to occur

**Screenshots**

**(please complete the following information):**
 - Lavalink4NET Version
   2.0.1-preview.1
 - Exception thrown? (consider enabling logging)
 ```
Method not found: 'System.Collections.Generic.IEnumerable`1<DSharpPlus.Entities.DiscordMember> DSharpPlus.Entities.DiscordChannel.get_Users()'.
Stack trace:
   at Lavalink4NET.DSharpPlus.DiscordClientWrapperBase.GetChannelUsersAsync(UInt64 guildId, UInt64 voiceChannelId)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Lavalink4NET.DSharpPlus.DiscordClientWrapperBase.GetChannelUsersAsync(UInt64 guildId, UInt64 voiceChannelId)
   at Lavalink4NET.Player.VoteLavalinkPlayer.GetVoteInfoAsync()
   at Lavalink4NET.Player.VoteLavalinkPlayer.VoteAsync(UInt64 userId, Single percentage)
```
**Additional context**

**Comment by angelobreuer** [comment]
Hello @Silverdimond,

thank you for your report!

It seems like that the commit https://github.com/DSharpPlus/DSharpPlus/commit/ec4d160b1fd84a12ceccc492a7aa27e3a5aa7c4b introduced a breaking ABI change and made Lavalink4NET incompatible with the new ABI.

I've bumped dependencies to recompile against the new API interface and push a release on NuGet.

Thanks, Angelo.
